---
resources:
  - name: app-resource
    type: git
    source:
      uri: https://github.com/tbatty7/kafka-streams.git
jobs:
  - name: kafka-job
    serial: true
    plan:
      - get: app-resource
      - task:
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: localhost:5000/java8 }
          inputs:
            - name: app-resource
          run:
            path: bash
            args:
              - -c
              - |
                ls -a
                cd app-resource
                ./gradlew test
